### ISSUE TITLE
Unable to compile ntfs-3g under macOS Monterey 12.6.1 (x86_64 or arm64)

### ISSUE THREAD

**Issue by kanadgodse-lh** [tuxera/ntfs-3g#68] opened 2022-12-08 11:59 UTC
I am trying to compile ntfs-3g from source on my MacBook Pro M1 running macOS Monterey 12.6.1 but it's failing with the same error for both x86_64 and arm64 architectures:

arm64:
Undefined symbols for architecture arm64:
  "_libintl_setlocale", referenced from:
      _utils_set_locale in utils.o
ld: symbol(s) not found for architecture arm64

x86_64:
Undefined symbols for architecture x86_64:
  "_libintl_setlocale", referenced from:
      _utils_set_locale in utils.o
ld: symbol(s) not found for architecture x86_64

I have already installed the following build tools
- Xcode and it's command line tools
- Brew and the following packages: automake, libtool, libgcrypt, pkg-config
- MacFUSE v4.4.1

Can someone please tell me how to proceed ahead?

P.S:

I am just downloading the tar.gz file, running autoconfig.sh, then ./configure but the make command is what's failing.

**Comment by unsound** [comment] 2022-12-08 15:36
Duplicate of issue https://github.com/tuxera/ntfs-3g/issues/5. Please check older issues before filing new ones.

**Closed as completed by unsound** 2022-12-08 15:36 UTC
