### ISSUE TITLE
how to support the other character set, such as GBK

### ISSUE THREAD

**Issue by wkt-huha** [tuxera/ntfs-3g#59] opened 2022-09-27 03:16 UTC
the system has support "zh_CN.gbk", and i mounted the usb disk by "mount -t ntfs-3g -o locale=zh_CN.gbk /dev/xxx /mount_path". But I still can not create gbk filename.
eg:
[root@RV1126_RV1109:/]# mount -t ntfs-3g -o locale=zh_CN.gbk /dev/sda1 /tmp/udisk/
[root@RV1126_RV1109:/]# 
[root@RV1126_RV1109:/]# cd /tmp/udisk/
[root@RV1126_RV1109:/tmp/udisk]# touch 你好
touch: cannot touch ''$'\304\343\272\303': Invalid or incomplete multibyte or wide character

**Comment by unsound** [comment] 2022-09-28 07:45
I cannot reproduce this, are you sure that your locale and terminal settings are all set to ```zh_CN.gbk```?

Here's my sequence of commands to try to reproduce (I first set my terminal to input gbk, see your terminal profile):
```
$ locale
LANG=zh_CN.gbk
LANGUAGE=zh_CN:zh
LC_CTYPE="zh_CN.gbk"
LC_NUMERIC="zh_CN.gbk"
LC_TIME="zh_CN.gbk"
LC_COLLATE="zh_CN.gbk"
LC_MONETARY="zh_CN.gbk"
LC_MESSAGES="zh_CN.gbk"
LC_PAPER="zh_CN.gbk"
LC_NAME="zh_CN.gbk"
LC_ADDRESS="zh_CN.gbk"
LC_TELEPHONE="zh_CN.gbk"
LC_MEASUREMENT="zh_CN.gbk"
LC_IDENTIFICATION="zh_CN.gbk"
LC_ALL=zh_CN.gbk
$ sudo src/ntfs-3g -olocale=zh_CN.gbk /dev/sdb1 mp
$ touch mp/你好
$ ls -l mp
total 0
-rwxrwxrwx  1 root root    0  9月 28 10:36 你好
$ sudo umount mp
$ sudo src/ntfs-3g -olocale=zh_CN.gbk /dev/sdb1 mp
$ ls -l mp
total 0
-rwxrwxrwx  1 root root    0  9月 28 10:36 你好
$ ls -1 mp | xxd
00000000: c4e3 bac3 0a                             .....
```
(The last command verifies that the encoding returned back from the filesystem is indeed gbk.)

**Comment by wkt-huha** [comment] 2022-09-28 13:06
It's quite strange, my locale and terminal settings are all set to zh_CN.gbk. Maybe the locale not working properly.My terminal is a embedded device, which is rochcdhip platform.
Hear's my setting:
```
[root@RV1126_RV1109:~]# locale
LANG=zh_CN.gbk
LC_CTYPE="zh_CN.gbk"
LC_NUMERIC="zh_CN.gbk"
LC_TIME="zh_CN.gbk"
LC_COLLATE="zh_CN.gbk"
LC_MONETARY="zh_CN.gbk"
LC_MESSAGES="zh_CN.gbk"
LC_PAPER="zh_CN.gbk"
LC_NAME="zh_CN.gbk"
LC_ADDRESS="zh_CN.gbk"
LC_TELEPHONE="zh_CN.gbk"
LC_MEASUREMENT="zh_CN.gbk"
LC_IDENTIFICATION="zh_CN.gbk"
LC_ALL=zh_CN.gbk

[root@RV1126_RV1109:~]# locale -a
C
POSIX
zh_CN.gb18030
zh_CN.gb2312
zh_CN.gbk
zh_CN.utf8
```

**Comment by unsound** [comment] 2022-09-28 13:20
I'm closing this as we cannot reproduce. It's likely to be a problem with your locale, but if you can reproduce on a desktop Linux distribution, like Ubuntu, Fedora, then we could take a look again.
If you need commercial support for integration with an embedded platform, then please check with sales@tuxera.com.

**Closed as completed by unsound** 2022-09-28 13:20 UTC
