### ISSUE TITLE
Error for mac 12.0.1 (2019 MacBook pro 16-inch) NTFS-3G 2021.8.22

### ISSUE THREAD

**Issue by Jaas-Wang** [tuxera/ntfs-3g#18] opened 2021-12-11 06:12 UTC
/bin/sh ../libtool  --tag=CC   --mode=link gcc  -g -O2 -Wall  -framework CoreFoundation -o ntfsfix ntfsfix.o utils.o ../libntfs-3g/libntfs-3g.la -lc 
libtool: link: gcc -g -O2 -Wall -o .libs/ntfsfix ntfsfix.o utils.o  ../libntfs-3g/.libs/libntfs-3g.dylib -lc -framework CoreFoundation
Undefined symbols for architecture x86_64:
  "_libintl_setlocale", referenced from:
      _utils_set_locale in utils.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [ntfsfix] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by unsound** [comment] 2021-12-15 15:54
Hi,

This is a duplicate of issue #5 so the same solution should apply.

**Closed as completed by unsound** 2021-12-15 15:54 UTC
